package com.careerlink.careerlink_backend.entity.enums;

public enum NotificationType {
    NEW_POST, JOB_POSTED, JOB_APPROVED, JOB_REJECTED,
    APPLICATION_RECEIVED, APPLICATION_SHORTLISTED, APPLICATION_REJECTED,
    APPLICATION_SELECTED, APPLICATION_PENDING,
    RECRUITER_PENDING, RECRUITER_APPROVED, RECRUITER_REJECTED,
    ALUMNI_PENDING, ALUMNI_APPROVED, ALUMNI_REJECTED,
    PROFILE_COMPLETED, EXTENSION_REQUESTED, EXTENSION_APPROVED, EXTENSION_REJECTED,
    REFERRAL_PENDING, REFERRAL_APPROVED, REFERRAL_REJECTED, REFERRAL_POSTED
}
